config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers:  {
      sessions: "admins/sessions"
  }
  devise_scope :admin do
    get '/admins/sign_out', to: 'devise/sessions#destroy', as: :signout
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "projects#index"
  get "/apprentices.html.erb" => "projects#apprentices"
  get "/admins" => "admins#index"
  get "/index.html.erb" => "projects#index"
  get "/projects.html.erb" => "projects#projects"
  get "/teams.html.erb" => "projects#teams"
  resources :projects
  resources :teams
  resources :apprentices
end

app/views/admins/index.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Huli</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand">Huli</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="index.html.erb">Home</a></li>
      <li><%= link_to "New Project", new_project_path %></li>
      <li><%= link_to "New Team", new_team_path %></li>
      <li><%= link_to "New Apprentice", new_apprentice_path %></li>
      <li><%= link_to "Sign Out", destroy_admin_session_path, method: :delete %></li>
    </ul>
  </div>
</nav>

<div class="container">
  <h2>The Projects</h2>          
  <table class="table table-bordered">
      <tr>
        <th>Avatar</th>
        <th>Project name</th>
        <th>Description</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    <% @projects.each do |project| %>
        <tr>
          <td><%= image_tag project.image.url%></td>
          <td><%= project.title %></td>
          <td><%= project.description %></td>
          <td><%= link_to "Edit", edit_project_path(project) %></td>
          <td><%= link_to "Delete", project, :confirm => "Are you sure?", :method => :delete %></td>
        </tr>
      <% end %>
  </table>
</div>
<div class="container">
<h2>The Teams</h2>
  <table class="table table-bordered">
  <tr>
    <th>Avatar</th>
    <th>Team name</th>
    <th>Apprentices</th>
    <th>Projects</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
<% @teams.each do |team| %>
    <tr>
      <td><%= image_tag team.image.url%></td>
      <td><%= team.name %></td>
      <td>
        <% team.apprentices.each_with_index do |a, index| %>
        <%= a.name %> 
        <%= ", " unless team.apprentices.size==index+1 %> 
          <% end %>
      </td>
      <td>
        <% team.projects.each_with_index do |p, index| %>
        <%= p.title %> 
        <%= ", " unless team.projects.size==index+1 %> 
          <% end %>
      </td>
      <td><%= link_to "Edit", edit_team_path(team) %></td>
      <td><%= link_to "Delete", team, :confirm => "Are you sure?", :method => :delete %></td>
    </tr>
  <% end %>
</table>
</div>
<div class="container">
<h2>The Apprentices</h2>
  <table class="table table-bordered">
  <tr>
    <th>Name</th>
    <th>GitHub</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <% @apprentices.each do |apprentice| %>
    <tr>
      <td><%= apprentice.name%></td>
      <td><%= apprentice.github %></td>
      <td><%= link_to "Edit", edit_apprentice_path(apprentice) %></td>
      <td><%= link_to "Delete", apprentice, :confirm => "Are you sure?", :method => :delete %></td>
    </tr>
  <% end %>
</table>
</div>
</body>
</html>